/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAiWorkspaceRouteImport } from './routes/_app.ai-workspace'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFleetRouteImport } from './routes/_app.fleet'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppManufacturingRouteImport } from './routes/_app.manufacturing'
import { Route as AppPredictiveRouteImport } from './routes/_app.predictive'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRootCauseRouteImport } from './routes/_app.root-cause'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppVehiclesRouteImport } from './routes/_app.vehicles'
import { Route as AppWarrantyRouteImport } from './routes/_app.warranty'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAiWorkspaceRoute = AppAiWorkspaceRouteImport.update({
  id: '/ai-workspace',
  path: '/ai-workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetRoute = AppFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppManufacturingRoute = AppManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictiveRoute = AppPredictiveRouteImport.update({
  id: '/predictive',
  path: '/predictive',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRootCauseRoute = AppRootCauseRouteImport.update({
  id: '/root-cause',
  path: '/root-cause',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppWarrantyRoute = AppWarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/ai-workspace': typeof AppAiWorkspaceRoute
  '/alerts': typeof AppAlertsRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/fleet': typeof AppFleetRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/manufacturing': typeof AppManufacturingRoute
  '/predictive': typeof AppPredictiveRoute
  '/reports': typeof AppReportsRoute
  '/root-cause': typeof AppRootCauseRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/support': typeof AppSupportRoute
  '/vehicles': typeof AppVehiclesRoute
  '/warranty': typeof AppWarrantyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/ai-workspace': typeof AppAiWorkspaceRoute
  '/alerts': typeof AppAlertsRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/fleet': typeof AppFleetRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/manufacturing': typeof AppManufacturingRoute
  '/predictive': typeof AppPredictiveRoute
  '/reports': typeof AppReportsRoute
  '/root-cause': typeof AppRootCauseRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/support': typeof AppSupportRoute
  '/vehicles': typeof AppVehiclesRoute
  '/warranty': typeof AppWarrantyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai-workspace': typeof AppAiWorkspaceRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fleet': typeof AppFleetRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/manufacturing': typeof AppManufacturingRoute
  '/_app/predictive': typeof AppPredictiveRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/root-cause': typeof AppRootCauseRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/vehicles': typeof AppVehiclesRoute
  '/_app/warranty': typeof AppWarrantyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/ai-workspace'
    | '/alerts'
    | '/billing'
    | '/dashboard'
    | '/fleet'
    | '/knowledge'
    | '/manufacturing'
    | '/predictive'
    | '/reports'
    | '/root-cause'
    | '/settings'
    | '/suppliers'
    | '/support'
    | '/vehicles'
    | '/warranty'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/ai-workspace'
    | '/alerts'
    | '/billing'
    | '/dashboard'
    | '/fleet'
    | '/knowledge'
    | '/manufacturing'
    | '/predictive'
    | '/reports'
    | '/root-cause'
    | '/settings'
    | '/suppliers'
    | '/support'
    | '/vehicles'
    | '/warranty'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/ai-workspace'
    | '/_app/alerts'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/fleet'
    | '/_app/knowledge'
    | '/_app/manufacturing'
    | '/_app/predictive'
    | '/_app/reports'
    | '/_app/root-cause'
    | '/_app/settings'
    | '/_app/suppliers'
    | '/_app/support'
    | '/_app/vehicles'
    | '/_app/warranty'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-workspace': {
      id: '/_app/ai-workspace'
      path: '/ai-workspace'
      fullPath: '/ai-workspace'
      preLoaderRoute: typeof AppAiWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet': {
      id: '/_app/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AppFleetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manufacturing': {
      id: '/_app/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof AppManufacturingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/predictive': {
      id: '/_app/predictive'
      path: '/predictive'
      fullPath: '/predictive'
      preLoaderRoute: typeof AppPredictiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/root-cause': {
      id: '/_app/root-cause'
      path: '/root-cause'
      fullPath: '/root-cause'
      preLoaderRoute: typeof AppRootCauseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicles': {
      id: '/_app/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warranty': {
      id: '/_app/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof AppWarrantyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiWorkspaceRoute: typeof AppAiWorkspaceRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFleetRoute: typeof AppFleetRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppManufacturingRoute: typeof AppManufacturingRoute
  AppPredictiveRoute: typeof AppPredictiveRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRootCauseRoute: typeof AppRootCauseRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppSupportRoute: typeof AppSupportRoute
  AppVehiclesRoute: typeof AppVehiclesRoute
  AppWarrantyRoute: typeof AppWarrantyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiWorkspaceRoute: AppAiWorkspaceRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFleetRoute: AppFleetRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppManufacturingRoute: AppManufacturingRoute,
  AppPredictiveRoute: AppPredictiveRoute,
  AppReportsRoute: AppReportsRoute,
  AppRootCauseRoute: AppRootCauseRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppSupportRoute: AppSupportRoute,
  AppVehiclesRoute: AppVehiclesRoute,
  AppWarrantyRoute: AppWarrantyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
